language: go

env:
  - GO111MODULE=on

go:
- "1.12"

before_install:
  - go get -t -v
 
script:
  - cd websocket
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
